### PR TITLE
feat: implement delete char, on ctrl-d and delete

### PR DESCRIPTION
**Pull request by quite**

### CODE REVIEW

**Comment by cblgh** [comment]
ping @mafintosh this is really nice! and will be directly used for https://github.com/cabal-club/cabal-cli :3

**Comment by mafintosh** [comment]
@cblgh should I add you to this?

**Comment by mafintosh** [comment]
1.11.0

**Comment by cblgh** [comment]
thanks @mafintosh!

> @cblgh should I add you to this?

i wouldn't mind

**Pull request merged**
