### PR TITLE
Add shift modifier

### PR DESCRIPTION
**Pull request by fabianhjr**
keypress code: https://github.com/TooTallNate/keypress/blob/9f1cc0ec7ac98a4aad0e0612ec14bf1b18c32eed/index.js#L185

### CODE REVIEW

**Comment by ghost** [comment]
It might be better to do this in the existing fall-through switch statement instead, with a prefix if shift is down:

```
83d82
<     var pre = key && key.shift ? 'shift-' : ''
86c85
<         input.emit(pre + 'up')
---
>         input.emit('up')
90c89
<         input.emit(pre + 'down')
---
>         input.emit('down')
95c94
<         input.emit(pre + 'left')
---
>         input.emit('left')
100c99
<         input.emit(pre + 'right')
---
>         input.emit('right')
105c104
<         input.emit(pre + 'delete')
---
>         input.emit('delete')
111c110
<         input.emit(pre + 'backspace')
---
>         input.emit('backspace')
115c114
<         input.emit(pre + 'pageup')
---
>         input.emit('pageup')
119c118
<         input.emit(pre + 'pagedown')
---
>         input.emit('pagedown')
124c123
<           input.emit(pre + 'tab')
---
>           input.emit('tab')
134c133
<           input.emit(pre + 'space')
---
>           input.emit('space')
```

**Comment by cblgh** [comment]
ping @mafintosh there's a [cabal pr](https://github.com/cabal-club/cabal-cli/pull/172) waiting for this to land :3

**Comment by cblgh** [comment]
fixed a `standard` error that made itself known when running `npm test`, closing this pr and merging in #12 :)

**Comment by cblgh** [comment]
published as `neat-input@1.11.1`

**Pull request closed without merging**
